#!/bin/bash

# Script to generate SysId serializers from Types.kt
# Usage: ./generate_sysid_serializers.sh
# This script should be run from the sysId directory where it's located

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# Use relative path from sysId directory to Types.kt (4 levels up to neome/)
TYPES_FILE="$SCRIPT_DIR/../../../../api/meta/base/Types.kt"
# Output file in the same directory as the script
OUTPUT_FILE="$SCRIPT_DIR/SerializerSysIdGenerated.kt"

if [ ! -f "$TYPES_FILE" ]; then
    echo "Error: Types.kt not found at $TYPES_FILE"
    exit 1
fi

echo "Parsing $TYPES_FILE..."

# Extract all SysId class names
CLASS_NAMES=$(grep "^  open class.*:" "$TYPES_FILE" | \
    grep -E "(SysId|ArtifactId|ChatId|ContactId|InboxId|MediaId|MetaId|MetaIdComp|MetaIdComposite|MetaIdPipelineParam)" | \
    sed 's/^  open class \([^ ]*\) : .*/\1/' | \
    sort)

CLASS_COUNT=$(echo "$CLASS_NAMES" | wc -l | tr -d ' ')
echo "Found $CLASS_COUNT SysId classes"

# Generate the output file
cat > "$OUTPUT_FILE" << 'HEADER'
// Auto-generated file. Do not edit manually.
// Generated by generate_sysid_serializers.sh

package com.neome.core.common.serializer.sysId

import com.neome.api.meta.base.Types

HEADER

# Generate serializer objects
echo "$CLASS_NAMES" | while read -r class_name; do
    if [ -n "$class_name" ]; then
        ser_name="${class_name}Ser"
        echo "object $ser_name : SysIdSerializer<Types.${class_name}>(\"${class_name}\")" >> "$OUTPUT_FILE"
    fi
done


echo "Generated $OUTPUT_FILE"
echo "Total serializers: $CLASS_COUNT"
echo "Done!"
