#!/bin/bash

# Script to generate SysId serializers from Types.kt
# Usage: ./generate_sysid_serializers.sh
# This script should be run from the sysId directory where it's located

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# Use relative path from sysId directory to Types.kt (4 levels up to neome/)
TYPES_FILE="$SCRIPT_DIR/../../../../api/meta/base/Types.kt"
# Output file in the same directory as the script
OUTPUT_FILE="$SCRIPT_DIR/SerializerSysIdGenerated.kt"

if [ ! -f "$TYPES_FILE" ]; then
    echo "Error: Types.kt not found at $TYPES_FILE"
    exit 1
fi

echo "Parsing $TYPES_FILE..."

# Extract all SysId class names
CLASS_NAMES=$(grep "^  open class.*:" "$TYPES_FILE" | \
    grep -E "(SysId|ArtifactId|ChatId|ContactId|InboxId|MediaId|MetaId|MetaIdComp|MetaIdComposite|MetaIdPipelineParam)" | \
    sed 's/^  open class \([^ ]*\) : .*/\1/' | \
    sort)

CLASS_COUNT=$(echo "$CLASS_NAMES" | wc -l | tr -d ' ')
echo "Found $CLASS_COUNT SysId classes"

# Generate the output file
cat > "$OUTPUT_FILE" << 'HEADER'
// Auto-generated file. Do not edit manually.
// Generated by generate_sysid_serializers.sh

package com.neome.core.common.serializer.sysId

import com.neome.api.meta.base.SysId
import com.neome.api.meta.base.Types
import kotlinx.serialization.KSerializer
import kotlin.reflect.KClass

HEADER

# Generate serializer objects
echo "$CLASS_NAMES" | while read -r class_name; do
    if [ -n "$class_name" ]; then
        ser_name="${class_name}Ser"
        echo "object $ser_name : SysIdSerializer<Types.${class_name}>(\"${class_name}\")" >> "$OUTPUT_FILE"
    fi
done

# Add blank line
echo "" >> "$OUTPUT_FILE"

# Generate the object class with map and functions
cat >> "$OUTPUT_FILE" << 'MAP_START'
/**
 * Registry for SysId serializers
 */
object SysIdSerializers {
    /**
     * Map from SysId class to its corresponding serializer
     */
    val serializerMap: Map<KClass<out SysId>, KSerializer<out SysId>> = mapOf(
MAP_START

# Generate map entries (with extra indentation for object)
LAST_CLASS=$(echo "$CLASS_NAMES" | tail -1)
echo "$CLASS_NAMES" | while read -r class_name; do
    if [ -n "$class_name" ]; then
        ser_name="${class_name}Ser"
        if [ "$class_name" = "$LAST_CLASS" ]; then
            echo "        Types.${class_name}::class to $ser_name" >> "$OUTPUT_FILE"
        else
            echo "        Types.${class_name}::class to $ser_name," >> "$OUTPUT_FILE"
        fi
    fi
done

cat >> "$OUTPUT_FILE" << 'MAP_END'
    )

    /**
     * Get serializer for a SysId class
     */
    @Suppress("UNCHECKED_CAST")
    fun <T : SysId> get(klass: KClass<T>): KSerializer<T>? {
        return serializerMap[klass] as? KSerializer<T>
    }

    /**
     * Get serializer for a SysId instance using reified type
     */
    @Suppress("UNCHECKED_CAST")
    inline fun <reified T : SysId> get(): KSerializer<T>? {
        return serializerMap[T::class] as? KSerializer<T>
    }
}
MAP_END

echo "Generated $OUTPUT_FILE"
echo "Total serializers: $CLASS_COUNT"
echo "Done!"
