#!/bin/bash

# Script to generate SysId serializers from Types.kt
# Usage: ./generate_sysid_serializers.sh
# This script should be run from the sysId directory where it's located

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# Use relative path from sysId directory to Types.kt (4 levels up to neome/)
TYPES_FILE="$SCRIPT_DIR/../../../../api/meta/base/Types.kt"
# Output file in the same directory as the script
OUTPUT_FILE="$SCRIPT_DIR/SerializerSysIdGenerated.kt"

if [ ! -f "$TYPES_FILE" ]; then
    echo "Error: Types.kt not found at $TYPES_FILE"
    exit 1
fi

echo "Parsing $TYPES_FILE..."

# Extract all SysId class names
CLASS_NAMES=$(grep "^  open class.*:" "$TYPES_FILE" | \
    grep -E "(SysId|ArtifactId|ChatId|ContactId|InboxId|MediaId|MetaId|MetaIdComp|MetaIdComposite|MetaIdPipelineParam)" | \
    sed 's/^  open class \([^ ]*\) : .*/\1/' | \
    sort)

CLASS_COUNT=$(echo "$CLASS_NAMES" | wc -l | tr -d ' ')
echo "Found $CLASS_COUNT SysId classes"

# Generate the output file with header and imports
cat > "$OUTPUT_FILE" << 'HEADER'
// Auto-generated file. Do not edit manually.
// Generated by generate_sysid_serializers.sh

package com.neome.core.common.serializer.sysId

// SysId imports
import com.neome.api.meta.base.Types

// AnyValue class imports (individual files)
import com.neome.api.meta.base.AnyEmailId
import com.neome.api.meta.base.AnyKey
import com.neome.api.meta.base.AnyName
import com.neome.api.meta.base.NanoId
import com.neome.api.meta.base.Symbol

// AnyValue class imports (from Types.kt classes)
import com.neome.api.meta.base.Types.AnyTime
import com.neome.api.meta.base.Types.ColumnPath
import com.neome.api.meta.base.Types.CurrencyKey
import com.neome.api.meta.base.Types.GeoPoint
import com.neome.api.meta.base.Types.HandleKey
import com.neome.api.meta.base.Types.Key
import com.neome.api.meta.base.Types.LanguageKey
import com.neome.api.meta.base.Types.SearchPath
import com.neome.api.meta.base.Types.SymbolColumn
import com.neome.api.meta.base.Types.SymbolGrid
import com.neome.api.meta.base.Types.TimeZoneKey

// AnyValue class imports (from nucleus/base/Types.kt)
import com.neome.api.nucleus.base.Types.AnyOtpValue
import com.neome.api.nucleus.base.Types.AnyPrefixKey
import com.neome.api.nucleus.base.Types.AppVersion

HEADER

# Generate SysId serializer objects
echo "$CLASS_NAMES" | while read -r class_name; do
    if [ -n "$class_name" ]; then
        ser_name="${class_name}Ser"
        echo "object $ser_name : SysIdSerializer<Types.${class_name}>(\"${class_name}\")" >> "$OUTPUT_FILE"
    fi
done

# Add blank line
echo "" >> "$OUTPUT_FILE"

# Generate AnyValue serializer objects
# Source locations:
# - Individual files in api/meta/base/: AnyEmailId, AnyKey, AnyName, NanoId, Symbol
# - api/meta/base/Types.kt: AnyTime, ColumnPath, CurrencyKey, GeoPoint, HandleKey,
#                           Key, LanguageKey, SearchPath, SymbolColumn, SymbolGrid, TimeZoneKey
# - api/nucleus/base/Types.kt: AnyOtpValue, AnyPrefixKey, AppVersion
ANY_VALUE_CLASSES=(
    "AnyEmailId"
    "AnyKey"
    "AnyName"
    "AnyOtpValue"
    "AnyPrefixKey"
    "AnyTime"
    "AppVersion"
    "ColumnPath"
    "CurrencyKey"
    "GeoPoint"
    "HandleKey"
    "Key"
    "LanguageKey"
    "NanoId"
    "SearchPath"
    "Symbol"
    "SymbolColumn"
    "SymbolGrid"
    "TimeZoneKey"
)

ANY_VALUE_COUNT=0
for class_name in "${ANY_VALUE_CLASSES[@]}"; do
    ser_name="${class_name}Ser"
    echo "object $ser_name : AnyValueSerializer<${class_name}>(\"${class_name}\", ${class_name}::class.java)" >> "$OUTPUT_FILE"
    ((ANY_VALUE_COUNT++))
done

TOTAL_COUNT=$((CLASS_COUNT + ANY_VALUE_COUNT))

echo "Generated $OUTPUT_FILE"
echo "SysId serializers: $CLASS_COUNT"
echo "AnyValue serializers: $ANY_VALUE_COUNT"
echo "Total serializers: $TOTAL_COUNT"
echo "Done!"
