// Auto-generated file. Do not edit manually.
// Generated by generate_sysid_serializers.sh

package com.neome.core.common.serializer.sysId

import com.neome.api.meta.base.SysId
import com.neome.api.meta.base.Types
import kotlinx.serialization.KSerializer
import kotlin.reflect.KClass

object AdminIdSer : SysIdSerializer<Types.AdminId>("AdminId")
object ArtifactIdSer : SysIdSerializer<Types.ArtifactId>("ArtifactId")
object AutomationExecutionIdSer : SysIdSerializer<Types.AutomationExecutionId>("AutomationExecutionId")
object ChatIdSer : SysIdSerializer<Types.ChatId>("ChatId")
object ConnIdSer : SysIdSerializer<Types.ConnId>("ConnId")
object ContactIdSer : SysIdSerializer<Types.ContactId>("ContactId")
object DemoAppIdSer : SysIdSerializer<Types.DemoAppId>("DemoAppId")
object DeviceIdSer : SysIdSerializer<Types.DeviceId>("DeviceId")
object EntIdSer : SysIdSerializer<Types.EntId>("EntId")
object EntUserIdSer : SysIdSerializer<Types.EntUserId>("EntUserId")
object GhostIdSer : SysIdSerializer<Types.GhostId>("GhostId")
object GroupIdSer : SysIdSerializer<Types.GroupId>("GroupId")
object InboxIdSer : SysIdSerializer<Types.InboxId>("InboxId")
object InboxIdFollowerSer : SysIdSerializer<Types.InboxIdFollower>("InboxIdFollower")
object InboxIdMasterSer : SysIdSerializer<Types.InboxIdMaster>("InboxIdMaster")
object InboxMessageIdSer : SysIdSerializer<Types.InboxMessageId>("InboxMessageId")
object KeychainIdSer : SysIdSerializer<Types.KeychainId>("KeychainId")
object KeychainSecretIdSer : SysIdSerializer<Types.KeychainSecretId>("KeychainSecretId")
object MediaIdSer : SysIdSerializer<Types.MediaId>("MediaId")
object MediaIdAudioSer : SysIdSerializer<Types.MediaIdAudio>("MediaIdAudio")
object MediaIdAvatarSer : SysIdSerializer<Types.MediaIdAvatar>("MediaIdAvatar")
object MediaIdDocumentSer : SysIdSerializer<Types.MediaIdDocument>("MediaIdDocument")
object MediaIdIconSer : SysIdSerializer<Types.MediaIdIcon>("MediaIdIcon")
object MediaIdImageSer : SysIdSerializer<Types.MediaIdImage>("MediaIdImage")
object MediaIdJarSer : SysIdSerializer<Types.MediaIdJar>("MediaIdJar")
object MediaIdStickerSer : SysIdSerializer<Types.MediaIdSticker>("MediaIdSticker")
object MediaIdThumbnailSer : SysIdSerializer<Types.MediaIdThumbnail>("MediaIdThumbnail")
object MediaIdVideoSer : SysIdSerializer<Types.MediaIdVideo>("MediaIdVideo")
object MediaIdVoiceSer : SysIdSerializer<Types.MediaIdVoice>("MediaIdVoice")
object MessageIdSer : SysIdSerializer<Types.MessageId>("MessageId")
object MetaIdSer : SysIdSerializer<Types.MetaId>("MetaId")
object MetaIdActionSer : SysIdSerializer<Types.MetaIdAction>("MetaIdAction")
object MetaIdAutomationSer : SysIdSerializer<Types.MetaIdAutomation>("MetaIdAutomation")
object MetaIdChartXAxisSer : SysIdSerializer<Types.MetaIdChartXAxis>("MetaIdChartXAxis")
object MetaIdChartYAxisSer : SysIdSerializer<Types.MetaIdChartYAxis>("MetaIdChartYAxis")
object MetaIdCodeSer : SysIdSerializer<Types.MetaIdCode>("MetaIdCode")
object MetaIdCompSer : SysIdSerializer<Types.MetaIdComp>("MetaIdComp")
object MetaIdCompositeSer : SysIdSerializer<Types.MetaIdComposite>("MetaIdComposite")
object MetaIdConditionSer : SysIdSerializer<Types.MetaIdCondition>("MetaIdCondition")
object MetaIdDeeplinkSer : SysIdSerializer<Types.MetaIdDeeplink>("MetaIdDeeplink")
object MetaIdDriveSheetSer : SysIdSerializer<Types.MetaIdDriveSheet>("MetaIdDriveSheet")
object MetaIdEventSer : SysIdSerializer<Types.MetaIdEvent>("MetaIdEvent")
object MetaIdFieldSer : SysIdSerializer<Types.MetaIdField>("MetaIdField")
object MetaIdFieldDynamicConditionSer : SysIdSerializer<Types.MetaIdFieldDynamicCondition>("MetaIdFieldDynamicCondition")
object MetaIdFieldDynamicRuleSer : SysIdSerializer<Types.MetaIdFieldDynamicRule>("MetaIdFieldDynamicRule")
object MetaIdFooterSer : SysIdSerializer<Types.MetaIdFooter>("MetaIdFooter")
object MetaIdFormSer : SysIdSerializer<Types.MetaIdForm>("MetaIdForm")
object MetaIdFormulaSer : SysIdSerializer<Types.MetaIdFormula>("MetaIdFormula")
object MetaIdFuncArgSer : SysIdSerializer<Types.MetaIdFuncArg>("MetaIdFuncArg")
object MetaIdGridSer : SysIdSerializer<Types.MetaIdGrid>("MetaIdGrid")
object MetaIdGroupSer : SysIdSerializer<Types.MetaIdGroup>("MetaIdGroup")
object MetaIdHeaderSer : SysIdSerializer<Types.MetaIdHeader>("MetaIdHeader")
object MetaIdHyperlinkSer : SysIdSerializer<Types.MetaIdHyperlink>("MetaIdHyperlink")
object MetaIdLayoutDriveSheetSer : SysIdSerializer<Types.MetaIdLayoutDriveSheet>("MetaIdLayoutDriveSheet")
object MetaIdLayoutFormSer : SysIdSerializer<Types.MetaIdLayoutForm>("MetaIdLayoutForm")
object MetaIdLayoutFormEditorCompositeSer : SysIdSerializer<Types.MetaIdLayoutFormEditorComposite>("MetaIdLayoutFormEditorComposite")
object MetaIdLayoutGridSer : SysIdSerializer<Types.MetaIdLayoutGrid>("MetaIdLayoutGrid")
object MetaIdLayoutUserSer : SysIdSerializer<Types.MetaIdLayoutUser>("MetaIdLayoutUser")
object MetaIdMappingSer : SysIdSerializer<Types.MetaIdMapping>("MetaIdMapping")
object MetaIdModuleSer : SysIdSerializer<Types.MetaIdModule>("MetaIdModule")
object MetaIdOptionSer : SysIdSerializer<Types.MetaIdOption>("MetaIdOption")
object MetaIdPartitionSer : SysIdSerializer<Types.MetaIdPartition>("MetaIdPartition")
object MetaIdPaymentProviderSer : SysIdSerializer<Types.MetaIdPaymentProvider>("MetaIdPaymentProvider")
object MetaIdPipelineParamSer : SysIdSerializer<Types.MetaIdPipelineParam>("MetaIdPipelineParam")
object MetaIdPipelineSystemSer : SysIdSerializer<Types.MetaIdPipelineSystem>("MetaIdPipelineSystem")
object MetaIdPipelineVarSer : SysIdSerializer<Types.MetaIdPipelineVar>("MetaIdPipelineVar")
object MetaIdPluginSer : SysIdSerializer<Types.MetaIdPlugin>("MetaIdPlugin")
object MetaIdPromptSer : SysIdSerializer<Types.MetaIdPrompt>("MetaIdPrompt")
object MetaIdReportSer : SysIdSerializer<Types.MetaIdReport>("MetaIdReport")
object MetaIdRoleSer : SysIdSerializer<Types.MetaIdRole>("MetaIdRole")
object MetaIdSectionSer : SysIdSerializer<Types.MetaIdSection>("MetaIdSection")
object MetaIdSpreadsheetSer : SysIdSerializer<Types.MetaIdSpreadsheet>("MetaIdSpreadsheet")
object MetaIdSpreadsheetRefSer : SysIdSerializer<Types.MetaIdSpreadsheetRef>("MetaIdSpreadsheetRef")
object MetaIdStepSer : SysIdSerializer<Types.MetaIdStep>("MetaIdStep")
object MetaIdSwimlaneSer : SysIdSerializer<Types.MetaIdSwimlane>("MetaIdSwimlane")
object MetaIdTabSer : SysIdSerializer<Types.MetaIdTab>("MetaIdTab")
object MetaIdTableStyleSer : SysIdSerializer<Types.MetaIdTableStyle>("MetaIdTableStyle")
object MetaIdTranslationSer : SysIdSerializer<Types.MetaIdTranslation>("MetaIdTranslation")
object MetaIdUserConditionSer : SysIdSerializer<Types.MetaIdUserCondition>("MetaIdUserCondition")
object MetaIdVarSer : SysIdSerializer<Types.MetaIdVar>("MetaIdVar")
object MetaIdVdAutoDiaSer : SysIdSerializer<Types.MetaIdVdAutoDia>("MetaIdVdAutoDia")
object MetaIdVdAutoEdgeSer : SysIdSerializer<Types.MetaIdVdAutoEdge>("MetaIdVdAutoEdge")
object MetaIdVdAutoFuncSer : SysIdSerializer<Types.MetaIdVdAutoFunc>("MetaIdVdAutoFunc")
object MetaIdVdAutoNodeSer : SysIdSerializer<Types.MetaIdVdAutoNode>("MetaIdVdAutoNode")
object MetaIdVdCommentSer : SysIdSerializer<Types.MetaIdVdComment>("MetaIdVdComment")
object MetaIdVdErdDiaSer : SysIdSerializer<Types.MetaIdVdErdDia>("MetaIdVdErdDia")
object MetaIdVdImageFuncSer : SysIdSerializer<Types.MetaIdVdImageFunc>("MetaIdVdImageFunc")
object MetaIdVdNoteSer : SysIdSerializer<Types.MetaIdVdNote>("MetaIdVdNote")
object MetaIdVdRegionSer : SysIdSerializer<Types.MetaIdVdRegion>("MetaIdVdRegion")
object MetaIdVdReportDiaSer : SysIdSerializer<Types.MetaIdVdReportDia>("MetaIdVdReportDia")
object MetaIdVdReviewSer : SysIdSerializer<Types.MetaIdVdReview>("MetaIdVdReview")
object MetaIdVideoTimestampSer : SysIdSerializer<Types.MetaIdVideoTimestamp>("MetaIdVideoTimestamp")
object MetaIdVisibilityActionSer : SysIdSerializer<Types.MetaIdVisibilityAction>("MetaIdVisibilityAction")
object MetaIdVisibilityConditionSer : SysIdSerializer<Types.MetaIdVisibilityCondition>("MetaIdVisibilityCondition")
object MetaIdVisibilityRuleSer : SysIdSerializer<Types.MetaIdVisibilityRule>("MetaIdVisibilityRule")
object MetaIdWizardSer : SysIdSerializer<Types.MetaIdWizard>("MetaIdWizard")
object PluginApiIdSer : SysIdSerializer<Types.PluginApiId>("PluginApiId")
object PluginBundleIdSer : SysIdSerializer<Types.PluginBundleId>("PluginBundleId")
object PluginIdSer : SysIdSerializer<Types.PluginId>("PluginId")
object PluginResourceIdSer : SysIdSerializer<Types.PluginResourceId>("PluginResourceId")
object ReportExecutionIdSer : SysIdSerializer<Types.ReportExecutionId>("ReportExecutionId")
object RequestIdSer : SysIdSerializer<Types.RequestId>("RequestId")
object RowIdSer : SysIdSerializer<Types.RowId>("RowId")
object SchedulerTaskIdSer : SysIdSerializer<Types.SchedulerTaskId>("SchedulerTaskId")
object SheetIdSer : SysIdSerializer<Types.SheetId>("SheetId")
object SnapshotIdSer : SysIdSerializer<Types.SnapshotId>("SnapshotId")
object SpreadsheetPartitionIdSer : SysIdSerializer<Types.SpreadsheetPartitionId>("SpreadsheetPartitionId")
object StoreItemIdSer : SysIdSerializer<Types.StoreItemId>("StoreItemId")
object TabIdSer : SysIdSerializer<Types.TabId>("TabId")
object TransactionIdSer : SysIdSerializer<Types.TransactionId>("TransactionId")
object UserIdSer : SysIdSerializer<Types.UserId>("UserId")
object WorkflowExecutionIdSer : SysIdSerializer<Types.WorkflowExecutionId>("WorkflowExecutionId")
object WorkflowGroupExecutionIdSer : SysIdSerializer<Types.WorkflowGroupExecutionId>("WorkflowGroupExecutionId")

/**
 * Registry for SysId serializers
 */
object SysIdSerializers {
    /**
     * Map from SysId class to its corresponding serializer
     */
    val serializerMap: Map<KClass<out SysId>, KSerializer<out SysId>> = mapOf(
        Types.AdminId::class to AdminIdSer,
        Types.ArtifactId::class to ArtifactIdSer,
        Types.AutomationExecutionId::class to AutomationExecutionIdSer,
        Types.ChatId::class to ChatIdSer,
        Types.ConnId::class to ConnIdSer,
        Types.ContactId::class to ContactIdSer,
        Types.DemoAppId::class to DemoAppIdSer,
        Types.DeviceId::class to DeviceIdSer,
        Types.EntId::class to EntIdSer,
        Types.EntUserId::class to EntUserIdSer,
        Types.GhostId::class to GhostIdSer,
        Types.GroupId::class to GroupIdSer,
        Types.InboxId::class to InboxIdSer,
        Types.InboxIdFollower::class to InboxIdFollowerSer,
        Types.InboxIdMaster::class to InboxIdMasterSer,
        Types.InboxMessageId::class to InboxMessageIdSer,
        Types.KeychainId::class to KeychainIdSer,
        Types.KeychainSecretId::class to KeychainSecretIdSer,
        Types.MediaId::class to MediaIdSer,
        Types.MediaIdAudio::class to MediaIdAudioSer,
        Types.MediaIdAvatar::class to MediaIdAvatarSer,
        Types.MediaIdDocument::class to MediaIdDocumentSer,
        Types.MediaIdIcon::class to MediaIdIconSer,
        Types.MediaIdImage::class to MediaIdImageSer,
        Types.MediaIdJar::class to MediaIdJarSer,
        Types.MediaIdSticker::class to MediaIdStickerSer,
        Types.MediaIdThumbnail::class to MediaIdThumbnailSer,
        Types.MediaIdVideo::class to MediaIdVideoSer,
        Types.MediaIdVoice::class to MediaIdVoiceSer,
        Types.MessageId::class to MessageIdSer,
        Types.MetaId::class to MetaIdSer,
        Types.MetaIdAction::class to MetaIdActionSer,
        Types.MetaIdAutomation::class to MetaIdAutomationSer,
        Types.MetaIdChartXAxis::class to MetaIdChartXAxisSer,
        Types.MetaIdChartYAxis::class to MetaIdChartYAxisSer,
        Types.MetaIdCode::class to MetaIdCodeSer,
        Types.MetaIdComp::class to MetaIdCompSer,
        Types.MetaIdComposite::class to MetaIdCompositeSer,
        Types.MetaIdCondition::class to MetaIdConditionSer,
        Types.MetaIdDeeplink::class to MetaIdDeeplinkSer,
        Types.MetaIdDriveSheet::class to MetaIdDriveSheetSer,
        Types.MetaIdEvent::class to MetaIdEventSer,
        Types.MetaIdField::class to MetaIdFieldSer,
        Types.MetaIdFieldDynamicCondition::class to MetaIdFieldDynamicConditionSer,
        Types.MetaIdFieldDynamicRule::class to MetaIdFieldDynamicRuleSer,
        Types.MetaIdFooter::class to MetaIdFooterSer,
        Types.MetaIdForm::class to MetaIdFormSer,
        Types.MetaIdFormula::class to MetaIdFormulaSer,
        Types.MetaIdFuncArg::class to MetaIdFuncArgSer,
        Types.MetaIdGrid::class to MetaIdGridSer,
        Types.MetaIdGroup::class to MetaIdGroupSer,
        Types.MetaIdHeader::class to MetaIdHeaderSer,
        Types.MetaIdHyperlink::class to MetaIdHyperlinkSer,
        Types.MetaIdLayoutDriveSheet::class to MetaIdLayoutDriveSheetSer,
        Types.MetaIdLayoutForm::class to MetaIdLayoutFormSer,
        Types.MetaIdLayoutFormEditorComposite::class to MetaIdLayoutFormEditorCompositeSer,
        Types.MetaIdLayoutGrid::class to MetaIdLayoutGridSer,
        Types.MetaIdLayoutUser::class to MetaIdLayoutUserSer,
        Types.MetaIdMapping::class to MetaIdMappingSer,
        Types.MetaIdModule::class to MetaIdModuleSer,
        Types.MetaIdOption::class to MetaIdOptionSer,
        Types.MetaIdPartition::class to MetaIdPartitionSer,
        Types.MetaIdPaymentProvider::class to MetaIdPaymentProviderSer,
        Types.MetaIdPipelineParam::class to MetaIdPipelineParamSer,
        Types.MetaIdPipelineSystem::class to MetaIdPipelineSystemSer,
        Types.MetaIdPipelineVar::class to MetaIdPipelineVarSer,
        Types.MetaIdPlugin::class to MetaIdPluginSer,
        Types.MetaIdPrompt::class to MetaIdPromptSer,
        Types.MetaIdReport::class to MetaIdReportSer,
        Types.MetaIdRole::class to MetaIdRoleSer,
        Types.MetaIdSection::class to MetaIdSectionSer,
        Types.MetaIdSpreadsheet::class to MetaIdSpreadsheetSer,
        Types.MetaIdSpreadsheetRef::class to MetaIdSpreadsheetRefSer,
        Types.MetaIdStep::class to MetaIdStepSer,
        Types.MetaIdSwimlane::class to MetaIdSwimlaneSer,
        Types.MetaIdTab::class to MetaIdTabSer,
        Types.MetaIdTableStyle::class to MetaIdTableStyleSer,
        Types.MetaIdTranslation::class to MetaIdTranslationSer,
        Types.MetaIdUserCondition::class to MetaIdUserConditionSer,
        Types.MetaIdVar::class to MetaIdVarSer,
        Types.MetaIdVdAutoDia::class to MetaIdVdAutoDiaSer,
        Types.MetaIdVdAutoEdge::class to MetaIdVdAutoEdgeSer,
        Types.MetaIdVdAutoFunc::class to MetaIdVdAutoFuncSer,
        Types.MetaIdVdAutoNode::class to MetaIdVdAutoNodeSer,
        Types.MetaIdVdComment::class to MetaIdVdCommentSer,
        Types.MetaIdVdErdDia::class to MetaIdVdErdDiaSer,
        Types.MetaIdVdImageFunc::class to MetaIdVdImageFuncSer,
        Types.MetaIdVdNote::class to MetaIdVdNoteSer,
        Types.MetaIdVdRegion::class to MetaIdVdRegionSer,
        Types.MetaIdVdReportDia::class to MetaIdVdReportDiaSer,
        Types.MetaIdVdReview::class to MetaIdVdReviewSer,
        Types.MetaIdVideoTimestamp::class to MetaIdVideoTimestampSer,
        Types.MetaIdVisibilityAction::class to MetaIdVisibilityActionSer,
        Types.MetaIdVisibilityCondition::class to MetaIdVisibilityConditionSer,
        Types.MetaIdVisibilityRule::class to MetaIdVisibilityRuleSer,
        Types.MetaIdWizard::class to MetaIdWizardSer,
        Types.PluginApiId::class to PluginApiIdSer,
        Types.PluginBundleId::class to PluginBundleIdSer,
        Types.PluginId::class to PluginIdSer,
        Types.PluginResourceId::class to PluginResourceIdSer,
        Types.ReportExecutionId::class to ReportExecutionIdSer,
        Types.RequestId::class to RequestIdSer,
        Types.RowId::class to RowIdSer,
        Types.SchedulerTaskId::class to SchedulerTaskIdSer,
        Types.SheetId::class to SheetIdSer,
        Types.SnapshotId::class to SnapshotIdSer,
        Types.SpreadsheetPartitionId::class to SpreadsheetPartitionIdSer,
        Types.StoreItemId::class to StoreItemIdSer,
        Types.TabId::class to TabIdSer,
        Types.TransactionId::class to TransactionIdSer,
        Types.UserId::class to UserIdSer,
        Types.WorkflowExecutionId::class to WorkflowExecutionIdSer,
        Types.WorkflowGroupExecutionId::class to WorkflowGroupExecutionIdSer
    )

    /**
     * Get serializer for a SysId class
     */
    @Suppress("UNCHECKED_CAST")
    fun <T : SysId> get(klass: KClass<T>): KSerializer<T>? {
        return serializerMap[klass] as? KSerializer<T>
    }

    /**
     * Get serializer for a SysId instance using reified type
     */
    @Suppress("UNCHECKED_CAST")
    inline fun <reified T : SysId> get(): KSerializer<T>? {
        return serializerMap[T::class] as? KSerializer<T>
    }
}
