package generator

val defnCompTypeMapping = mapOf(
    // basic
    "DefnFieldSwitch" to "bool",
    "DefnFieldDate" to "date",
    "DefnFieldDecimal" to "decimal",
    "DefnFieldLogDecimal" to "logDecimal",
    "DefnFieldImage" to "image",
    "DefnFieldLabel" to "label",
    "DefnFieldNumber" to "number",
    "DefnFieldLogNumber" to "logNumber",
    "DefnFieldParagraph" to "paragraph",
    "DefnFieldText" to "text",

    // chipset
    "DefnFieldChipSet" to "chipSet",
    "DefnFieldChipSetDate" to "chipSetDate",
    "DefnFieldChipSetDateTime" to "chipSetDateTime",
    "DefnFieldChipSetDay" to "chipSetDay",
    "DefnFieldChipSetDeviceSize" to "chipSetDeviceSize",
    "DefnFieldChipSetDeviceType" to "chipSetDeviceType",
    "DefnFieldChipSetTime" to "chipSetTime",

    // picker
    "DefnFieldPickRole" to "pickRole",
    "DefnFieldPickText" to "pickText",
    "DefnFieldPickTree" to "pickTree",
    "DefnFieldPickUser" to "pickUser",
    "DefnFieldPickGridRow" to "pickGridRow",
    "DefnFieldPickReportRow" to "pickReportRow",
    "DefnFieldSetOfRole" to "setOfRole",
    "DefnFieldSetOfUser" to "setOfUser",
    "DefnFieldSetOfText" to "setOfText",

    // advanced
    "DefnFieldColor" to "color",
    "DefnFieldHyperlink" to "hyperlink",
    "DefnFieldAudio" to "audio",
    "DefnFieldCamera" to "camera",
    "DefnFieldCounter" to "counter",
    "DefnFieldLogCounter" to "logCounter",
    "DefnFieldDateRange" to "dateRange",
    "DefnFieldDateTime" to "dateTime",
    "DefnFieldDateTimeRange" to "dateTimeRange",
    "DefnFieldDuration" to "duration",
    "DefnFieldEmail" to "email",
    "DefnFieldHandle" to "handle",
    "DefnFieldLocation" to "location",
    "DefnFieldMobileNumber" to "mobileNumber",
    "DefnFieldRating" to "rating",
    "DefnFieldSignature" to "signature",
    "DefnFieldSlider" to "slider",
    "DefnFieldTime" to "time",
    "DefnFieldVideo" to "video",
    "DefnFieldVoice" to "voice",
    "DefnFieldGeoPoint" to "geoPoint",

    // pro
    "DefnFieldRowId" to "rowId",
    "DefnFieldSymbol" to "symbol",
    "DefnFieldSchedulerId" to "schedulerId",
    "DefnFieldButton" to "button",
    "DefnFieldDivider" to "divider",
    "DefnFieldDocument" to "document",
    "DefnFieldError" to "error",
    "DefnFieldHtml" to "html",
    "DefnFieldIdentifier" to "identifier",
    "DefnFieldInfo" to "info",
    "DefnFieldPropertyMap" to "propertyMap",
    "DefnFieldScanCode" to "scanCode",
    "DefnFieldSetOfDocument" to "setOfDocument",
    "DefnFieldShowCode" to "showCode",
    "DefnFieldUserId" to "userId",
    "DefnFieldDynamic" to "dynamic",
    "DefnFieldHyperlinkRow" to "hyperlinkRow",
    "DefnFieldPassword" to "password",

    // ref
    "DefnFieldRef" to "ref",
    "DefnFieldRefSet" to "refSet",
    "DefnFieldRefUser" to "refUser",
    "DefnFieldRefReport" to "refReport",
    "DefnFieldRefTarget" to "refTarget",
    "DefnFieldRefContact" to "refContact",

    // composite
    "DefnGrid" to "grid",
    "DefnSection" to "section",
    "DefnSpreadsheetRef" to "spreadsheetRef",
    "DefnTab" to "tab",
    "DefnWizard" to "wizard",

    // enums and fields (shared DefnFieldPickEnum and DefnFieldEditable)
    "DefnFieldPickEnum" to "enumAdminDoNotOptionEnt",
    "DefnFieldEditable" to "enumPaymentMethodKind",
    "DefnFieldCurrency" to "currency",
    "DefnFieldIcon" to "icon",
    "DefnFieldLanguage" to "language",
    "DefnFieldTimeZone" to "timeZone",
    "DefnFieldPinShape" to "pinShape",
    "DefnFieldLineStroke" to "lineStroke",
    "DefnFieldMonth" to "month",
    "DefnFieldQuarter" to "quarter",
    "DefnFieldTextSize" to "textSize",
    "DefnFieldPaymentStatus" to "paymentStatus",
    "DefnFieldMessageType" to "messageKind",

    // studio
    "DefnStudioVarIdTextEditor" to "studioVarIdTextEditor",
    "DefnStudioVarIdParagraphEditor" to "studioVarIdParagraphEditor",
    "DefnStudioCodeEditor" to "studioCodeEditor",
    "DefnStudioPickActionId" to "pickActionId",
    "DefnStudioPickCompId" to "pickCompId",
    "DefnStudioPickPluginCompId" to "pickPluginCompId",
    "DefnStudioPickFieldId" to "pickFieldId",
    "DefnStudioPickPluginFieldId" to "pickPluginFieldId",
    "DefnStudioPickFormId" to "pickFormId",
    "DefnStudioPickPluginFormId" to "pickPluginFormId",
    "DefnStudioPickGridId" to "pickGridId",
    "DefnStudioPickImportPluginId" to "pickImportPluginId",
    "DefnStudioPickImportPluginApiId" to "pickImportPluginApiId",
    "DefnStudioPickLayoutFormContentId" to "pickLayoutFormContentId",
    "DefnStudioPickLayoutGridId" to "pickLayoutGridId",
    "DefnStudioPickSpreadsheetRefLayoutId" to "pickSpreadsheetRefLayoutId",
    "DefnStudioPickLayoutSpreadsheetId" to "pickLayoutSpreadsheetId",
    "DefnStudioPickPluginBundleId" to "pickPluginBundleId",
    "DefnStudioPickPluginId" to "pickPluginId",
    "DefnStudioPickReportId" to "pickReportId",
    "DefnStudioPickSectionId" to "pickSectionId",
    "DefnStudioPickSpreadsheetId" to "pickSpreadsheetId",
    "DefnStudioPickVarId" to "pickVarId",
    "DefnStudioPickGroupId" to "pickGroupId",
    "DefnStudioPickDeeplinkId" to "pickDeeplinkId",
    "DefnStudioPickPipelineVarId" to "pickPipelineVarId",
    "DefnStudioPickAutomationId" to "pickAutomationId",
    "DefnStudioBuildAllModules" to "studioBuildAllModules",
    "DefnStudioBuildArgBinder" to "studioBuildArgBinder",
    "DefnStudioSetOfDate" to "studioSetOfDate",
    "DefnStudioBuildColor" to "studioBuildColor",
    "DefnStudioBuildDate" to "studioBuildDate",
    "DefnStudioBuildDateTime" to "studioBuildDateTime",
    "DefnStudioBuildPermissionMatrix" to "studioBuildPermissionMatrix",
    "DefnStudioBuildTree" to "studioBuildTree",
    "DefnStudioBuildUserSetting" to "studioBuildUserSetting",
    "DefnStudioBuildActionPermission" to "studioBuildActionPermission",
    "DefnStudioBuildPropertyMap" to "studioBuildPropertyMap",
    "DefnStudioBuildMapping" to "studioBuildMapping",
    "DefnStudioBuildOptionPermissionMatrix" to "studioBuildOptionPermissionMatrix",
    "DefnStudioMapOfForwardRolePermission" to "studioMapOfForwardRolePermission",
    "DefnStudioMapOfCondition" to "studioMapOfCondition",
    "DefnStudioMapOfFormula" to "studioMapOfFormula",
    "DefnStudioMapOfFuncArg" to "studioMapOfFuncArg",
    "DefnStudioMapOfJarFile" to "studioMapOfJarFile",
    "DefnStudioMapOfLayoutSpreadsheet" to "studioMapOfLayoutSpreadsheet",
    "DefnStudioMapOfLayoutGrid" to "studioMapOfLayoutGrid",
    "DefnStudioMapOfText" to "studioMapOfText",
    "DefnStudioMapOfVisibilityCondition" to "studioMapOfVisibilityCondition",
    "DefnStudioMapOfVisibilityAction" to "studioMapOfVisibilityAction",
    "DefnStudioMapOfPartition" to "studioMapOfPartition",
    "DefnStudioMapOfForwardGroupPermission" to "studioMapOfForwardGroupPermission",
    "DefnStudioMapOfDynamicRule" to "studioMapOfDynamicRule",
    "DefnStudioMapOfPipelineVariable" to "studioMapOfPipelineVariable",
    "DefnStudioMapOfDynamicCondition" to "studioMapOfDynamicCondition",
    "DefnStudioMapOfUserCondition" to "studioMapOfUserCondition",
    "DefnStudioMapOfLayoutDriveSheet" to "studioMapOfLayoutDriveSpreadsheet",
    "DefnStudioMapOfMapping" to "studioFieldMappingTree",
    "DefnStudioMapOfArgBinder" to "studioMapOfArgBinder",
    "DefnStudioBuildRefTargetSpreadsheet" to "studioMapOfRefTargetSpreadsheet",
    "DefnStudioSetOfDocFileExt" to "studioSetOfDocFileExt",
    "DefnStudioSetOfStoreItemCategory" to "studioSetOfStoreItemCategory",
    "DefnStudioSetOfModule" to "studioSetOfModule",
    "DefnStudioSetOfNumber" to "studioSetOfNumber",
    "DefnStudioSetOfAdminDoNotOption" to "studioSetOfAdminDoNotOption",
    "DefnStudioSetOfPluginSecurityAccess" to "studioSetOfPluginSecurityAccess",
    "DefnStudioSetOfRowAuditTrail" to "studioSetOfRowAuditTrail",
    "DefnStudioSetOfMonth" to "studioSetOfMonth",
    "DefnStudioSetOfActionId" to "studioSetOfActionId",
    "DefnStudioSetOfFieldRefId" to "studioSetOfFieldRefId",
    "DefnStudioSetOfLayoutFormContentId" to "studioSetOfLayoutFormContentId",
    "DefnStudioSetOfLayoutGridId" to "studioSetOfLayoutGridId",
    "DefnStudioSetOfReportId" to "studioSetOfReportId",
    "DefnStudioCompArray" to "studioCompArray",

    // uionly
    "DefnFieldOtp" to "otp",
    "DefnFieldAvtar" to "avtar",
    "DefnFieldCarousel" to "carousel",
    "DefnFieldFormList" to "formList",
    "DefnFieldFormListItem" to "formListItem",
    "DefnFieldPickOption" to "pickOption"
)
